In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [7]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [6]:
## Define the vocabulary size
voc_size=10000

In [8]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7149, 8602, 887, 7414],
 [7149, 8602, 887, 881],
 [7149, 7022, 887, 2701],
 [4445, 4607, 439, 9199, 810],
 [4445, 4607, 439, 9199, 2626],
 [6341, 7149, 32, 887, 4014],
 [3962, 2898, 6328, 9199]]

In [13]:
## word Embedding Representation
 
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [14]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7149 8602  887 7414]
 [   0    0    0    0 7149 8602  887  881]
 [   0    0    0    0 7149 7022  887 2701]
 [   0    0    0 4445 4607  439 9199  810]
 [   0    0    0 4445 4607  439 9199 2626]
 [   0    0    0 6341 7149   32  887 4014]
 [   0    0    0    0 3962 2898 6328 9199]]


In [16]:
## feature representation
dim=10
model = Sequential()
model.add(Embedding(voc_size, dim, input_shape=(sent_length,)))

model.compile(optimizer='adam', loss='mse')

In [18]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
### Hidden State Formula

Hidden State = function(previous hidden state + current input)

SyntaxError: invalid syntax (4055620282.py, line 3)